/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgbRouteImport } from './routes/agb'
import { Route as DatenschutzRouteImport } from './routes/datenschutz'
import { Route as ImpressumRouteImport } from './routes/impressum'
import { Route as LeistungenRouteImport } from './routes/leistungen'
import { Route as UeberUnsRouteImport } from './routes/ueber-uns'
import { Route as DachIndexRouteImport } from './routes/dach/index'
import { Route as DachDachdaemmungRouteImport } from './routes/dach/dachdaemmung'
import { Route as DachDachfensterRouteImport } from './routes/dach/dachfenster'
import { Route as DachDachgaubenRouteImport } from './routes/dach/dachgauben'
import { Route as DachDachsanierungRouteImport } from './routes/dach/dachsanierung'
import { Route as DachKlempnerarbeitenRouteImport } from './routes/dach/klempnerarbeiten'
import { Route as FassadeIndexRouteImport } from './routes/fassade/index'
import { Route as FassadeHolzfassadeRouteImport } from './routes/fassade/holzfassade'
import { Route as FassadeTerrasseRouteImport } from './routes/fassade/terrasse'
import { Route as FassadeWaermedaemmungRouteImport } from './routes/fassade/waermedaemmung'
import { Route as HolzbauIndexRouteImport } from './routes/holzbau/index'
import { Route as HolzbauAufstockungenRouteImport } from './routes/holzbau/aufstockungen'
import { Route as HolzbauCarportRouteImport } from './routes/holzbau/carport'
import { Route as HolzbauDachstuhlRouteImport } from './routes/holzbau/dachstuhl'
import { Route as HolzbauHolzhausbauRouteImport } from './routes/holzbau/holzhausbau'
import { Route as KarriereIndexRouteImport } from './routes/karriere/index'
import { Route as KarriereBauhelferRouteImport } from './routes/karriere/bauhelfer'
import { Route as KarriereDachdeckerRouteImport } from './routes/karriere/dachdecker'
import { Route as KarriereDachdeckerAusbildungRouteImport } from './routes/karriere/dachdecker-ausbildung'
import { Route as KarriereZimmererRouteImport } from './routes/karriere/zimmerer'
import { Route as KarriereZimmermannAusbildungRouteImport } from './routes/karriere/zimmermann-ausbildung'
import { Route as KontaktIndexRouteImport } from './routes/kontakt/index'
import { Route as KontaktDankeRouteImport } from './routes/kontakt/danke'
import { Route as RatgeberIndexRouteImport } from './routes/ratgeber/index'
import { Route as RatgeberDachgaubenEinbauenRouteImport } from './routes/ratgeber/dachgauben-einbauen'
import { Route as RatgeberDenkmalschutzRouteImport } from './routes/ratgeber/denkmalschutz'
import { Route as RatgeberHolzAlsBaustoffRouteImport } from './routes/ratgeber/holz-als-baustoff'
import { Route as RatgeberHolzfassadenRouteImport } from './routes/ratgeber/holzfassaden'
import { Route as RatgeberKfwDachsanierungRouteImport } from './routes/ratgeber/kfw-dachsanierung'
import { Route as ReferenzenIndexRouteImport } from './routes/referenzen/index'
import { Route as ReferenzenDachRouteImport } from './routes/referenzen/dach'
import { Route as ReferenzenFassadeRouteImport } from './routes/referenzen/fassade'
import { Route as ReferenzenHolzbauRouteImport } from './routes/referenzen/holzbau'
import { Route as ReferenzenRestaurierungRouteImport } from './routes/referenzen/restaurierung'
import { Route as ReferenzenServicesRouteImport } from './routes/referenzen/services'
import { Route as RestaurierungIndexRouteImport } from './routes/restaurierung/index'
import { Route as RestaurierungDenkmalschutzRouteImport } from './routes/restaurierung/denkmalschutz'
import { Route as RestaurierungFachwerksanierungRouteImport } from './routes/restaurierung/fachwerksanierung'
import { Route as RestaurierungSchadenskartierungRouteImport } from './routes/restaurierung/schadenskartierung'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as ServicesLadekranRouteImport } from './routes/services/ladekran'
import { Route as ServicesShowroomRouteImport } from './routes/services/showroom'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgbRoute = AgbRouteImport.update({
  id: '/agb',
  path: '/agb',
  getParentRoute: () => rootRouteImport,
} as any)
const DatenschutzRoute = DatenschutzRouteImport.update({
  id: '/datenschutz',
  path: '/datenschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpressumRoute = ImpressumRouteImport.update({
  id: '/impressum',
  path: '/impressum',
  getParentRoute: () => rootRouteImport,
} as any)
const LeistungenRoute = LeistungenRouteImport.update({
  id: '/leistungen',
  path: '/leistungen',
  getParentRoute: () => rootRouteImport,
} as any)
const UeberUnsRoute = UeberUnsRouteImport.update({
  id: '/ueber-uns',
  path: '/ueber-uns',
  getParentRoute: () => rootRouteImport,
} as any)
const DachIndexRoute = DachIndexRouteImport.update({
  id: '/dach/',
  path: '/dach/',
  getParentRoute: () => rootRouteImport,
} as any)
const DachDachdaemmungRoute = DachDachdaemmungRouteImport.update({
  id: '/dach/dachdaemmung',
  path: '/dach/dachdaemmung',
  getParentRoute: () => rootRouteImport,
} as any)
const DachDachfensterRoute = DachDachfensterRouteImport.update({
  id: '/dach/dachfenster',
  path: '/dach/dachfenster',
  getParentRoute: () => rootRouteImport,
} as any)
const DachDachgaubenRoute = DachDachgaubenRouteImport.update({
  id: '/dach/dachgauben',
  path: '/dach/dachgauben',
  getParentRoute: () => rootRouteImport,
} as any)
const DachDachsanierungRoute = DachDachsanierungRouteImport.update({
  id: '/dach/dachsanierung',
  path: '/dach/dachsanierung',
  getParentRoute: () => rootRouteImport,
} as any)
const DachKlempnerarbeitenRoute = DachKlempnerarbeitenRouteImport.update({
  id: '/dach/klempnerarbeiten',
  path: '/dach/klempnerarbeiten',
  getParentRoute: () => rootRouteImport,
} as any)
const FassadeIndexRoute = FassadeIndexRouteImport.update({
  id: '/fassade/',
  path: '/fassade/',
  getParentRoute: () => rootRouteImport,
} as any)
const FassadeHolzfassadeRoute = FassadeHolzfassadeRouteImport.update({
  id: '/fassade/holzfassade',
  path: '/fassade/holzfassade',
  getParentRoute: () => rootRouteImport,
} as any)
const FassadeTerrasseRoute = FassadeTerrasseRouteImport.update({
  id: '/fassade/terrasse',
  path: '/fassade/terrasse',
  getParentRoute: () => rootRouteImport,
} as any)
const FassadeWaermedaemmungRoute = FassadeWaermedaemmungRouteImport.update({
  id: '/fassade/waermedaemmung',
  path: '/fassade/waermedaemmung',
  getParentRoute: () => rootRouteImport,
} as any)
const HolzbauIndexRoute = HolzbauIndexRouteImport.update({
  id: '/holzbau/',
  path: '/holzbau/',
  getParentRoute: () => rootRouteImport,
} as any)
const HolzbauAufstockungenRoute = HolzbauAufstockungenRouteImport.update({
  id: '/holzbau/aufstockungen',
  path: '/holzbau/aufstockungen',
  getParentRoute: () => rootRouteImport,
} as any)
const HolzbauCarportRoute = HolzbauCarportRouteImport.update({
  id: '/holzbau/carport',
  path: '/holzbau/carport',
  getParentRoute: () => rootRouteImport,
} as any)
const HolzbauDachstuhlRoute = HolzbauDachstuhlRouteImport.update({
  id: '/holzbau/dachstuhl',
  path: '/holzbau/dachstuhl',
  getParentRoute: () => rootRouteImport,
} as any)
const HolzbauHolzhausbauRoute = HolzbauHolzhausbauRouteImport.update({
  id: '/holzbau/holzhausbau',
  path: '/holzbau/holzhausbau',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereIndexRoute = KarriereIndexRouteImport.update({
  id: '/karriere/',
  path: '/karriere/',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereBauhelferRoute = KarriereBauhelferRouteImport.update({
  id: '/karriere/bauhelfer',
  path: '/karriere/bauhelfer',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereDachdeckerRoute = KarriereDachdeckerRouteImport.update({
  id: '/karriere/dachdecker',
  path: '/karriere/dachdecker',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereDachdeckerAusbildungRoute =
  KarriereDachdeckerAusbildungRouteImport.update({
    id: '/karriere/dachdecker-ausbildung',
    path: '/karriere/dachdecker-ausbildung',
    getParentRoute: () => rootRouteImport,
  } as any)
const KarriereZimmererRoute = KarriereZimmererRouteImport.update({
  id: '/karriere/zimmerer',
  path: '/karriere/zimmerer',
  getParentRoute: () => rootRouteImport,
} as any)
const KarriereZimmermannAusbildungRoute =
  KarriereZimmermannAusbildungRouteImport.update({
    id: '/karriere/zimmermann-ausbildung',
    path: '/karriere/zimmermann-ausbildung',
    getParentRoute: () => rootRouteImport,
  } as any)
const KontaktIndexRoute = KontaktIndexRouteImport.update({
  id: '/kontakt/',
  path: '/kontakt/',
  getParentRoute: () => rootRouteImport,
} as any)
const KontaktDankeRoute = KontaktDankeRouteImport.update({
  id: '/kontakt/danke',
  path: '/kontakt/danke',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberIndexRoute = RatgeberIndexRouteImport.update({
  id: '/ratgeber/',
  path: '/ratgeber/',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberDachgaubenEinbauenRoute =
  RatgeberDachgaubenEinbauenRouteImport.update({
    id: '/ratgeber/dachgauben-einbauen',
    path: '/ratgeber/dachgauben-einbauen',
    getParentRoute: () => rootRouteImport,
  } as any)
const RatgeberDenkmalschutzRoute = RatgeberDenkmalschutzRouteImport.update({
  id: '/ratgeber/denkmalschutz',
  path: '/ratgeber/denkmalschutz',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberHolzAlsBaustoffRoute = RatgeberHolzAlsBaustoffRouteImport.update({
  id: '/ratgeber/holz-als-baustoff',
  path: '/ratgeber/holz-als-baustoff',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberHolzfassadenRoute = RatgeberHolzfassadenRouteImport.update({
  id: '/ratgeber/holzfassaden',
  path: '/ratgeber/holzfassaden',
  getParentRoute: () => rootRouteImport,
} as any)
const RatgeberKfwDachsanierungRoute =
  RatgeberKfwDachsanierungRouteImport.update({
    id: '/ratgeber/kfw-dachsanierung',
    path: '/ratgeber/kfw-dachsanierung',
    getParentRoute: () => rootRouteImport,
  } as any)
const ReferenzenIndexRoute = ReferenzenIndexRouteImport.update({
  id: '/referenzen/',
  path: '/referenzen/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenDachRoute = ReferenzenDachRouteImport.update({
  id: '/referenzen/dach',
  path: '/referenzen/dach',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenFassadeRoute = ReferenzenFassadeRouteImport.update({
  id: '/referenzen/fassade',
  path: '/referenzen/fassade',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenHolzbauRoute = ReferenzenHolzbauRouteImport.update({
  id: '/referenzen/holzbau',
  path: '/referenzen/holzbau',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenRestaurierungRoute = ReferenzenRestaurierungRouteImport.update({
  id: '/referenzen/restaurierung',
  path: '/referenzen/restaurierung',
  getParentRoute: () => rootRouteImport,
} as any)
const ReferenzenServicesRoute = ReferenzenServicesRouteImport.update({
  id: '/referenzen/services',
  path: '/referenzen/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurierungIndexRoute = RestaurierungIndexRouteImport.update({
  id: '/restaurierung/',
  path: '/restaurierung/',
  getParentRoute: () => rootRouteImport,
} as any)
const RestaurierungDenkmalschutzRoute =
  RestaurierungDenkmalschutzRouteImport.update({
    id: '/restaurierung/denkmalschutz',
    path: '/restaurierung/denkmalschutz',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurierungFachwerksanierungRoute =
  RestaurierungFachwerksanierungRouteImport.update({
    id: '/restaurierung/fachwerksanierung',
    path: '/restaurierung/fachwerksanierung',
    getParentRoute: () => rootRouteImport,
  } as any)
const RestaurierungSchadenskartierungRoute =
  RestaurierungSchadenskartierungRouteImport.update({
    id: '/restaurierung/schadenskartierung',
    path: '/restaurierung/schadenskartierung',
    getParentRoute: () => rootRouteImport,
  } as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/services/',
  path: '/services/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesLadekranRoute = ServicesLadekranRouteImport.update({
  id: '/services/ladekran',
  path: '/services/ladekran',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesShowroomRoute = ServicesShowroomRouteImport.update({
  id: '/services/showroom',
  path: '/services/showroom',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/dach/dachdaemmung': typeof DachDachdaemmungRoute
  '/dach/dachfenster': typeof DachDachfensterRoute
  '/dach/dachgauben': typeof DachDachgaubenRoute
  '/dach/dachsanierung': typeof DachDachsanierungRoute
  '/dach/klempnerarbeiten': typeof DachKlempnerarbeitenRoute
  '/fassade/holzfassade': typeof FassadeHolzfassadeRoute
  '/fassade/terrasse': typeof FassadeTerrasseRoute
  '/fassade/waermedaemmung': typeof FassadeWaermedaemmungRoute
  '/holzbau/aufstockungen': typeof HolzbauAufstockungenRoute
  '/holzbau/carport': typeof HolzbauCarportRoute
  '/holzbau/dachstuhl': typeof HolzbauDachstuhlRoute
  '/holzbau/holzhausbau': typeof HolzbauHolzhausbauRoute
  '/karriere/bauhelfer': typeof KarriereBauhelferRoute
  '/karriere/dachdecker': typeof KarriereDachdeckerRoute
  '/karriere/dachdecker-ausbildung': typeof KarriereDachdeckerAusbildungRoute
  '/karriere/zimmerer': typeof KarriereZimmererRoute
  '/karriere/zimmermann-ausbildung': typeof KarriereZimmermannAusbildungRoute
  '/kontakt/danke': typeof KontaktDankeRoute
  '/ratgeber/dachgauben-einbauen': typeof RatgeberDachgaubenEinbauenRoute
  '/ratgeber/denkmalschutz': typeof RatgeberDenkmalschutzRoute
  '/ratgeber/holz-als-baustoff': typeof RatgeberHolzAlsBaustoffRoute
  '/ratgeber/holzfassaden': typeof RatgeberHolzfassadenRoute
  '/ratgeber/kfw-dachsanierung': typeof RatgeberKfwDachsanierungRoute
  '/referenzen/dach': typeof ReferenzenDachRoute
  '/referenzen/fassade': typeof ReferenzenFassadeRoute
  '/referenzen/holzbau': typeof ReferenzenHolzbauRoute
  '/referenzen/restaurierung': typeof ReferenzenRestaurierungRoute
  '/referenzen/services': typeof ReferenzenServicesRoute
  '/restaurierung/denkmalschutz': typeof RestaurierungDenkmalschutzRoute
  '/restaurierung/fachwerksanierung': typeof RestaurierungFachwerksanierungRoute
  '/restaurierung/schadenskartierung': typeof RestaurierungSchadenskartierungRoute
  '/services/ladekran': typeof ServicesLadekranRoute
  '/services/showroom': typeof ServicesShowroomRoute
  '/dach/': typeof DachIndexRoute
  '/fassade/': typeof FassadeIndexRoute
  '/holzbau/': typeof HolzbauIndexRoute
  '/karriere/': typeof KarriereIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/referenzen/': typeof ReferenzenIndexRoute
  '/restaurierung/': typeof RestaurierungIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/dach/dachdaemmung': typeof DachDachdaemmungRoute
  '/dach/dachfenster': typeof DachDachfensterRoute
  '/dach/dachgauben': typeof DachDachgaubenRoute
  '/dach/dachsanierung': typeof DachDachsanierungRoute
  '/dach/klempnerarbeiten': typeof DachKlempnerarbeitenRoute
  '/fassade/holzfassade': typeof FassadeHolzfassadeRoute
  '/fassade/terrasse': typeof FassadeTerrasseRoute
  '/fassade/waermedaemmung': typeof FassadeWaermedaemmungRoute
  '/holzbau/aufstockungen': typeof HolzbauAufstockungenRoute
  '/holzbau/carport': typeof HolzbauCarportRoute
  '/holzbau/dachstuhl': typeof HolzbauDachstuhlRoute
  '/holzbau/holzhausbau': typeof HolzbauHolzhausbauRoute
  '/karriere/bauhelfer': typeof KarriereBauhelferRoute
  '/karriere/dachdecker': typeof KarriereDachdeckerRoute
  '/karriere/dachdecker-ausbildung': typeof KarriereDachdeckerAusbildungRoute
  '/karriere/zimmerer': typeof KarriereZimmererRoute
  '/karriere/zimmermann-ausbildung': typeof KarriereZimmermannAusbildungRoute
  '/kontakt/danke': typeof KontaktDankeRoute
  '/ratgeber/dachgauben-einbauen': typeof RatgeberDachgaubenEinbauenRoute
  '/ratgeber/denkmalschutz': typeof RatgeberDenkmalschutzRoute
  '/ratgeber/holz-als-baustoff': typeof RatgeberHolzAlsBaustoffRoute
  '/ratgeber/holzfassaden': typeof RatgeberHolzfassadenRoute
  '/ratgeber/kfw-dachsanierung': typeof RatgeberKfwDachsanierungRoute
  '/referenzen/dach': typeof ReferenzenDachRoute
  '/referenzen/fassade': typeof ReferenzenFassadeRoute
  '/referenzen/holzbau': typeof ReferenzenHolzbauRoute
  '/referenzen/restaurierung': typeof ReferenzenRestaurierungRoute
  '/referenzen/services': typeof ReferenzenServicesRoute
  '/restaurierung/denkmalschutz': typeof RestaurierungDenkmalschutzRoute
  '/restaurierung/fachwerksanierung': typeof RestaurierungFachwerksanierungRoute
  '/restaurierung/schadenskartierung': typeof RestaurierungSchadenskartierungRoute
  '/services/ladekran': typeof ServicesLadekranRoute
  '/services/showroom': typeof ServicesShowroomRoute
  '/dach': typeof DachIndexRoute
  '/fassade': typeof FassadeIndexRoute
  '/holzbau': typeof HolzbauIndexRoute
  '/karriere': typeof KarriereIndexRoute
  '/kontakt': typeof KontaktIndexRoute
  '/ratgeber': typeof RatgeberIndexRoute
  '/referenzen': typeof ReferenzenIndexRoute
  '/restaurierung': typeof RestaurierungIndexRoute
  '/services': typeof ServicesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agb': typeof AgbRoute
  '/datenschutz': typeof DatenschutzRoute
  '/impressum': typeof ImpressumRoute
  '/leistungen': typeof LeistungenRoute
  '/ueber-uns': typeof UeberUnsRoute
  '/dach/dachdaemmung': typeof DachDachdaemmungRoute
  '/dach/dachfenster': typeof DachDachfensterRoute
  '/dach/dachgauben': typeof DachDachgaubenRoute
  '/dach/dachsanierung': typeof DachDachsanierungRoute
  '/dach/klempnerarbeiten': typeof DachKlempnerarbeitenRoute
  '/fassade/holzfassade': typeof FassadeHolzfassadeRoute
  '/fassade/terrasse': typeof FassadeTerrasseRoute
  '/fassade/waermedaemmung': typeof FassadeWaermedaemmungRoute
  '/holzbau/aufstockungen': typeof HolzbauAufstockungenRoute
  '/holzbau/carport': typeof HolzbauCarportRoute
  '/holzbau/dachstuhl': typeof HolzbauDachstuhlRoute
  '/holzbau/holzhausbau': typeof HolzbauHolzhausbauRoute
  '/karriere/bauhelfer': typeof KarriereBauhelferRoute
  '/karriere/dachdecker': typeof KarriereDachdeckerRoute
  '/karriere/dachdecker-ausbildung': typeof KarriereDachdeckerAusbildungRoute
  '/karriere/zimmerer': typeof KarriereZimmererRoute
  '/karriere/zimmermann-ausbildung': typeof KarriereZimmermannAusbildungRoute
  '/kontakt/danke': typeof KontaktDankeRoute
  '/ratgeber/dachgauben-einbauen': typeof RatgeberDachgaubenEinbauenRoute
  '/ratgeber/denkmalschutz': typeof RatgeberDenkmalschutzRoute
  '/ratgeber/holz-als-baustoff': typeof RatgeberHolzAlsBaustoffRoute
  '/ratgeber/holzfassaden': typeof RatgeberHolzfassadenRoute
  '/ratgeber/kfw-dachsanierung': typeof RatgeberKfwDachsanierungRoute
  '/referenzen/dach': typeof ReferenzenDachRoute
  '/referenzen/fassade': typeof ReferenzenFassadeRoute
  '/referenzen/holzbau': typeof ReferenzenHolzbauRoute
  '/referenzen/restaurierung': typeof ReferenzenRestaurierungRoute
  '/referenzen/services': typeof ReferenzenServicesRoute
  '/restaurierung/denkmalschutz': typeof RestaurierungDenkmalschutzRoute
  '/restaurierung/fachwerksanierung': typeof RestaurierungFachwerksanierungRoute
  '/restaurierung/schadenskartierung': typeof RestaurierungSchadenskartierungRoute
  '/services/ladekran': typeof ServicesLadekranRoute
  '/services/showroom': typeof ServicesShowroomRoute
  '/dach/': typeof DachIndexRoute
  '/fassade/': typeof FassadeIndexRoute
  '/holzbau/': typeof HolzbauIndexRoute
  '/karriere/': typeof KarriereIndexRoute
  '/kontakt/': typeof KontaktIndexRoute
  '/ratgeber/': typeof RatgeberIndexRoute
  '/referenzen/': typeof ReferenzenIndexRoute
  '/restaurierung/': typeof RestaurierungIndexRoute
  '/services/': typeof ServicesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/leistungen'
    | '/ueber-uns'
    | '/dach/dachdaemmung'
    | '/dach/dachfenster'
    | '/dach/dachgauben'
    | '/dach/dachsanierung'
    | '/dach/klempnerarbeiten'
    | '/fassade/holzfassade'
    | '/fassade/terrasse'
    | '/fassade/waermedaemmung'
    | '/holzbau/aufstockungen'
    | '/holzbau/carport'
    | '/holzbau/dachstuhl'
    | '/holzbau/holzhausbau'
    | '/karriere/bauhelfer'
    | '/karriere/dachdecker'
    | '/karriere/dachdecker-ausbildung'
    | '/karriere/zimmerer'
    | '/karriere/zimmermann-ausbildung'
    | '/kontakt/danke'
    | '/ratgeber/dachgauben-einbauen'
    | '/ratgeber/denkmalschutz'
    | '/ratgeber/holz-als-baustoff'
    | '/ratgeber/holzfassaden'
    | '/ratgeber/kfw-dachsanierung'
    | '/referenzen/dach'
    | '/referenzen/fassade'
    | '/referenzen/holzbau'
    | '/referenzen/restaurierung'
    | '/referenzen/services'
    | '/restaurierung/denkmalschutz'
    | '/restaurierung/fachwerksanierung'
    | '/restaurierung/schadenskartierung'
    | '/services/ladekran'
    | '/services/showroom'
    | '/dach/'
    | '/fassade/'
    | '/holzbau/'
    | '/karriere/'
    | '/kontakt/'
    | '/ratgeber/'
    | '/referenzen/'
    | '/restaurierung/'
    | '/services/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/leistungen'
    | '/ueber-uns'
    | '/dach/dachdaemmung'
    | '/dach/dachfenster'
    | '/dach/dachgauben'
    | '/dach/dachsanierung'
    | '/dach/klempnerarbeiten'
    | '/fassade/holzfassade'
    | '/fassade/terrasse'
    | '/fassade/waermedaemmung'
    | '/holzbau/aufstockungen'
    | '/holzbau/carport'
    | '/holzbau/dachstuhl'
    | '/holzbau/holzhausbau'
    | '/karriere/bauhelfer'
    | '/karriere/dachdecker'
    | '/karriere/dachdecker-ausbildung'
    | '/karriere/zimmerer'
    | '/karriere/zimmermann-ausbildung'
    | '/kontakt/danke'
    | '/ratgeber/dachgauben-einbauen'
    | '/ratgeber/denkmalschutz'
    | '/ratgeber/holz-als-baustoff'
    | '/ratgeber/holzfassaden'
    | '/ratgeber/kfw-dachsanierung'
    | '/referenzen/dach'
    | '/referenzen/fassade'
    | '/referenzen/holzbau'
    | '/referenzen/restaurierung'
    | '/referenzen/services'
    | '/restaurierung/denkmalschutz'
    | '/restaurierung/fachwerksanierung'
    | '/restaurierung/schadenskartierung'
    | '/services/ladekran'
    | '/services/showroom'
    | '/dach'
    | '/fassade'
    | '/holzbau'
    | '/karriere'
    | '/kontakt'
    | '/ratgeber'
    | '/referenzen'
    | '/restaurierung'
    | '/services'
  id:
    | '__root__'
    | '/'
    | '/agb'
    | '/datenschutz'
    | '/impressum'
    | '/leistungen'
    | '/ueber-uns'
    | '/dach/dachdaemmung'
    | '/dach/dachfenster'
    | '/dach/dachgauben'
    | '/dach/dachsanierung'
    | '/dach/klempnerarbeiten'
    | '/fassade/holzfassade'
    | '/fassade/terrasse'
    | '/fassade/waermedaemmung'
    | '/holzbau/aufstockungen'
    | '/holzbau/carport'
    | '/holzbau/dachstuhl'
    | '/holzbau/holzhausbau'
    | '/karriere/bauhelfer'
    | '/karriere/dachdecker'
    | '/karriere/dachdecker-ausbildung'
    | '/karriere/zimmerer'
    | '/karriere/zimmermann-ausbildung'
    | '/kontakt/danke'
    | '/ratgeber/dachgauben-einbauen'
    | '/ratgeber/denkmalschutz'
    | '/ratgeber/holz-als-baustoff'
    | '/ratgeber/holzfassaden'
    | '/ratgeber/kfw-dachsanierung'
    | '/referenzen/dach'
    | '/referenzen/fassade'
    | '/referenzen/holzbau'
    | '/referenzen/restaurierung'
    | '/referenzen/services'
    | '/restaurierung/denkmalschutz'
    | '/restaurierung/fachwerksanierung'
    | '/restaurierung/schadenskartierung'
    | '/services/ladekran'
    | '/services/showroom'
    | '/dach/'
    | '/fassade/'
    | '/holzbau/'
    | '/karriere/'
    | '/kontakt/'
    | '/ratgeber/'
    | '/referenzen/'
    | '/restaurierung/'
    | '/services/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgbRoute: typeof AgbRoute
  DatenschutzRoute: typeof DatenschutzRoute
  ImpressumRoute: typeof ImpressumRoute
  LeistungenRoute: typeof LeistungenRoute
  UeberUnsRoute: typeof UeberUnsRoute
  DachDachdaemmungRoute: typeof DachDachdaemmungRoute
  DachDachfensterRoute: typeof DachDachfensterRoute
  DachDachgaubenRoute: typeof DachDachgaubenRoute
  DachDachsanierungRoute: typeof DachDachsanierungRoute
  DachKlempnerarbeitenRoute: typeof DachKlempnerarbeitenRoute
  FassadeHolzfassadeRoute: typeof FassadeHolzfassadeRoute
  FassadeTerrasseRoute: typeof FassadeTerrasseRoute
  FassadeWaermedaemmungRoute: typeof FassadeWaermedaemmungRoute
  HolzbauAufstockungenRoute: typeof HolzbauAufstockungenRoute
  HolzbauCarportRoute: typeof HolzbauCarportRoute
  HolzbauDachstuhlRoute: typeof HolzbauDachstuhlRoute
  HolzbauHolzhausbauRoute: typeof HolzbauHolzhausbauRoute
  KarriereBauhelferRoute: typeof KarriereBauhelferRoute
  KarriereDachdeckerRoute: typeof KarriereDachdeckerRoute
  KarriereDachdeckerAusbildungRoute: typeof KarriereDachdeckerAusbildungRoute
  KarriereZimmererRoute: typeof KarriereZimmererRoute
  KarriereZimmermannAusbildungRoute: typeof KarriereZimmermannAusbildungRoute
  KontaktDankeRoute: typeof KontaktDankeRoute
  RatgeberDachgaubenEinbauenRoute: typeof RatgeberDachgaubenEinbauenRoute
  RatgeberDenkmalschutzRoute: typeof RatgeberDenkmalschutzRoute
  RatgeberHolzAlsBaustoffRoute: typeof RatgeberHolzAlsBaustoffRoute
  RatgeberHolzfassadenRoute: typeof RatgeberHolzfassadenRoute
  RatgeberKfwDachsanierungRoute: typeof RatgeberKfwDachsanierungRoute
  ReferenzenDachRoute: typeof ReferenzenDachRoute
  ReferenzenFassadeRoute: typeof ReferenzenFassadeRoute
  ReferenzenHolzbauRoute: typeof ReferenzenHolzbauRoute
  ReferenzenRestaurierungRoute: typeof ReferenzenRestaurierungRoute
  ReferenzenServicesRoute: typeof ReferenzenServicesRoute
  RestaurierungDenkmalschutzRoute: typeof RestaurierungDenkmalschutzRoute
  RestaurierungFachwerksanierungRoute: typeof RestaurierungFachwerksanierungRoute
  RestaurierungSchadenskartierungRoute: typeof RestaurierungSchadenskartierungRoute
  ServicesLadekranRoute: typeof ServicesLadekranRoute
  ServicesShowroomRoute: typeof ServicesShowroomRoute
  DachIndexRoute: typeof DachIndexRoute
  FassadeIndexRoute: typeof FassadeIndexRoute
  HolzbauIndexRoute: typeof HolzbauIndexRoute
  KarriereIndexRoute: typeof KarriereIndexRoute
  KontaktIndexRoute: typeof KontaktIndexRoute
  RatgeberIndexRoute: typeof RatgeberIndexRoute
  ReferenzenIndexRoute: typeof ReferenzenIndexRoute
  RestaurierungIndexRoute: typeof RestaurierungIndexRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agb': {
      id: '/agb'
      path: '/agb'
      fullPath: '/agb'
      preLoaderRoute: typeof AgbRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/datenschutz': {
      id: '/datenschutz'
      path: '/datenschutz'
      fullPath: '/datenschutz'
      preLoaderRoute: typeof DatenschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impressum': {
      id: '/impressum'
      path: '/impressum'
      fullPath: '/impressum'
      preLoaderRoute: typeof ImpressumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leistungen': {
      id: '/leistungen'
      path: '/leistungen'
      fullPath: '/leistungen'
      preLoaderRoute: typeof LeistungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ueber-uns': {
      id: '/ueber-uns'
      path: '/ueber-uns'
      fullPath: '/ueber-uns'
      preLoaderRoute: typeof UeberUnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dach/': {
      id: '/dach/'
      path: '/dach'
      fullPath: '/dach/'
      preLoaderRoute: typeof DachIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dach/dachdaemmung': {
      id: '/dach/dachdaemmung'
      path: '/dach/dachdaemmung'
      fullPath: '/dach/dachdaemmung'
      preLoaderRoute: typeof DachDachdaemmungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dach/dachfenster': {
      id: '/dach/dachfenster'
      path: '/dach/dachfenster'
      fullPath: '/dach/dachfenster'
      preLoaderRoute: typeof DachDachfensterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dach/dachgauben': {
      id: '/dach/dachgauben'
      path: '/dach/dachgauben'
      fullPath: '/dach/dachgauben'
      preLoaderRoute: typeof DachDachgaubenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dach/dachsanierung': {
      id: '/dach/dachsanierung'
      path: '/dach/dachsanierung'
      fullPath: '/dach/dachsanierung'
      preLoaderRoute: typeof DachDachsanierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dach/klempnerarbeiten': {
      id: '/dach/klempnerarbeiten'
      path: '/dach/klempnerarbeiten'
      fullPath: '/dach/klempnerarbeiten'
      preLoaderRoute: typeof DachKlempnerarbeitenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fassade/': {
      id: '/fassade/'
      path: '/fassade'
      fullPath: '/fassade/'
      preLoaderRoute: typeof FassadeIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fassade/holzfassade': {
      id: '/fassade/holzfassade'
      path: '/fassade/holzfassade'
      fullPath: '/fassade/holzfassade'
      preLoaderRoute: typeof FassadeHolzfassadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fassade/terrasse': {
      id: '/fassade/terrasse'
      path: '/fassade/terrasse'
      fullPath: '/fassade/terrasse'
      preLoaderRoute: typeof FassadeTerrasseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fassade/waermedaemmung': {
      id: '/fassade/waermedaemmung'
      path: '/fassade/waermedaemmung'
      fullPath: '/fassade/waermedaemmung'
      preLoaderRoute: typeof FassadeWaermedaemmungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holzbau/': {
      id: '/holzbau/'
      path: '/holzbau'
      fullPath: '/holzbau/'
      preLoaderRoute: typeof HolzbauIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holzbau/aufstockungen': {
      id: '/holzbau/aufstockungen'
      path: '/holzbau/aufstockungen'
      fullPath: '/holzbau/aufstockungen'
      preLoaderRoute: typeof HolzbauAufstockungenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holzbau/carport': {
      id: '/holzbau/carport'
      path: '/holzbau/carport'
      fullPath: '/holzbau/carport'
      preLoaderRoute: typeof HolzbauCarportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holzbau/dachstuhl': {
      id: '/holzbau/dachstuhl'
      path: '/holzbau/dachstuhl'
      fullPath: '/holzbau/dachstuhl'
      preLoaderRoute: typeof HolzbauDachstuhlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/holzbau/holzhausbau': {
      id: '/holzbau/holzhausbau'
      path: '/holzbau/holzhausbau'
      fullPath: '/holzbau/holzhausbau'
      preLoaderRoute: typeof HolzbauHolzhausbauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/': {
      id: '/karriere/'
      path: '/karriere'
      fullPath: '/karriere/'
      preLoaderRoute: typeof KarriereIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/bauhelfer': {
      id: '/karriere/bauhelfer'
      path: '/karriere/bauhelfer'
      fullPath: '/karriere/bauhelfer'
      preLoaderRoute: typeof KarriereBauhelferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/dachdecker': {
      id: '/karriere/dachdecker'
      path: '/karriere/dachdecker'
      fullPath: '/karriere/dachdecker'
      preLoaderRoute: typeof KarriereDachdeckerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/dachdecker-ausbildung': {
      id: '/karriere/dachdecker-ausbildung'
      path: '/karriere/dachdecker-ausbildung'
      fullPath: '/karriere/dachdecker-ausbildung'
      preLoaderRoute: typeof KarriereDachdeckerAusbildungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/zimmerer': {
      id: '/karriere/zimmerer'
      path: '/karriere/zimmerer'
      fullPath: '/karriere/zimmerer'
      preLoaderRoute: typeof KarriereZimmererRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/karriere/zimmermann-ausbildung': {
      id: '/karriere/zimmermann-ausbildung'
      path: '/karriere/zimmermann-ausbildung'
      fullPath: '/karriere/zimmermann-ausbildung'
      preLoaderRoute: typeof KarriereZimmermannAusbildungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt/': {
      id: '/kontakt/'
      path: '/kontakt'
      fullPath: '/kontakt/'
      preLoaderRoute: typeof KontaktIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kontakt/danke': {
      id: '/kontakt/danke'
      path: '/kontakt/danke'
      fullPath: '/kontakt/danke'
      preLoaderRoute: typeof KontaktDankeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/': {
      id: '/ratgeber/'
      path: '/ratgeber'
      fullPath: '/ratgeber/'
      preLoaderRoute: typeof RatgeberIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/dachgauben-einbauen': {
      id: '/ratgeber/dachgauben-einbauen'
      path: '/ratgeber/dachgauben-einbauen'
      fullPath: '/ratgeber/dachgauben-einbauen'
      preLoaderRoute: typeof RatgeberDachgaubenEinbauenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/denkmalschutz': {
      id: '/ratgeber/denkmalschutz'
      path: '/ratgeber/denkmalschutz'
      fullPath: '/ratgeber/denkmalschutz'
      preLoaderRoute: typeof RatgeberDenkmalschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/holz-als-baustoff': {
      id: '/ratgeber/holz-als-baustoff'
      path: '/ratgeber/holz-als-baustoff'
      fullPath: '/ratgeber/holz-als-baustoff'
      preLoaderRoute: typeof RatgeberHolzAlsBaustoffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/holzfassaden': {
      id: '/ratgeber/holzfassaden'
      path: '/ratgeber/holzfassaden'
      fullPath: '/ratgeber/holzfassaden'
      preLoaderRoute: typeof RatgeberHolzfassadenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ratgeber/kfw-dachsanierung': {
      id: '/ratgeber/kfw-dachsanierung'
      path: '/ratgeber/kfw-dachsanierung'
      fullPath: '/ratgeber/kfw-dachsanierung'
      preLoaderRoute: typeof RatgeberKfwDachsanierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/': {
      id: '/referenzen/'
      path: '/referenzen'
      fullPath: '/referenzen/'
      preLoaderRoute: typeof ReferenzenIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/dach': {
      id: '/referenzen/dach'
      path: '/referenzen/dach'
      fullPath: '/referenzen/dach'
      preLoaderRoute: typeof ReferenzenDachRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/fassade': {
      id: '/referenzen/fassade'
      path: '/referenzen/fassade'
      fullPath: '/referenzen/fassade'
      preLoaderRoute: typeof ReferenzenFassadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/holzbau': {
      id: '/referenzen/holzbau'
      path: '/referenzen/holzbau'
      fullPath: '/referenzen/holzbau'
      preLoaderRoute: typeof ReferenzenHolzbauRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/restaurierung': {
      id: '/referenzen/restaurierung'
      path: '/referenzen/restaurierung'
      fullPath: '/referenzen/restaurierung'
      preLoaderRoute: typeof ReferenzenRestaurierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/referenzen/services': {
      id: '/referenzen/services'
      path: '/referenzen/services'
      fullPath: '/referenzen/services'
      preLoaderRoute: typeof ReferenzenServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurierung/': {
      id: '/restaurierung/'
      path: '/restaurierung'
      fullPath: '/restaurierung/'
      preLoaderRoute: typeof RestaurierungIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurierung/denkmalschutz': {
      id: '/restaurierung/denkmalschutz'
      path: '/restaurierung/denkmalschutz'
      fullPath: '/restaurierung/denkmalschutz'
      preLoaderRoute: typeof RestaurierungDenkmalschutzRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurierung/fachwerksanierung': {
      id: '/restaurierung/fachwerksanierung'
      path: '/restaurierung/fachwerksanierung'
      fullPath: '/restaurierung/fachwerksanierung'
      preLoaderRoute: typeof RestaurierungFachwerksanierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/restaurierung/schadenskartierung': {
      id: '/restaurierung/schadenskartierung'
      path: '/restaurierung/schadenskartierung'
      fullPath: '/restaurierung/schadenskartierung'
      preLoaderRoute: typeof RestaurierungSchadenskartierungRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/services'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/ladekran': {
      id: '/services/ladekran'
      path: '/services/ladekran'
      fullPath: '/services/ladekran'
      preLoaderRoute: typeof ServicesLadekranRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/showroom': {
      id: '/services/showroom'
      path: '/services/showroom'
      fullPath: '/services/showroom'
      preLoaderRoute: typeof ServicesShowroomRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgbRoute: AgbRoute,
  DatenschutzRoute: DatenschutzRoute,
  ImpressumRoute: ImpressumRoute,
  LeistungenRoute: LeistungenRoute,
  UeberUnsRoute: UeberUnsRoute,
  DachDachdaemmungRoute: DachDachdaemmungRoute,
  DachDachfensterRoute: DachDachfensterRoute,
  DachDachgaubenRoute: DachDachgaubenRoute,
  DachDachsanierungRoute: DachDachsanierungRoute,
  DachKlempnerarbeitenRoute: DachKlempnerarbeitenRoute,
  FassadeHolzfassadeRoute: FassadeHolzfassadeRoute,
  FassadeTerrasseRoute: FassadeTerrasseRoute,
  FassadeWaermedaemmungRoute: FassadeWaermedaemmungRoute,
  HolzbauAufstockungenRoute: HolzbauAufstockungenRoute,
  HolzbauCarportRoute: HolzbauCarportRoute,
  HolzbauDachstuhlRoute: HolzbauDachstuhlRoute,
  HolzbauHolzhausbauRoute: HolzbauHolzhausbauRoute,
  KarriereBauhelferRoute: KarriereBauhelferRoute,
  KarriereDachdeckerRoute: KarriereDachdeckerRoute,
  KarriereDachdeckerAusbildungRoute: KarriereDachdeckerAusbildungRoute,
  KarriereZimmererRoute: KarriereZimmererRoute,
  KarriereZimmermannAusbildungRoute: KarriereZimmermannAusbildungRoute,
  KontaktDankeRoute: KontaktDankeRoute,
  RatgeberDachgaubenEinbauenRoute: RatgeberDachgaubenEinbauenRoute,
  RatgeberDenkmalschutzRoute: RatgeberDenkmalschutzRoute,
  RatgeberHolzAlsBaustoffRoute: RatgeberHolzAlsBaustoffRoute,
  RatgeberHolzfassadenRoute: RatgeberHolzfassadenRoute,
  RatgeberKfwDachsanierungRoute: RatgeberKfwDachsanierungRoute,
  ReferenzenDachRoute: ReferenzenDachRoute,
  ReferenzenFassadeRoute: ReferenzenFassadeRoute,
  ReferenzenHolzbauRoute: ReferenzenHolzbauRoute,
  ReferenzenRestaurierungRoute: ReferenzenRestaurierungRoute,
  ReferenzenServicesRoute: ReferenzenServicesRoute,
  RestaurierungDenkmalschutzRoute: RestaurierungDenkmalschutzRoute,
  RestaurierungFachwerksanierungRoute: RestaurierungFachwerksanierungRoute,
  RestaurierungSchadenskartierungRoute: RestaurierungSchadenskartierungRoute,
  ServicesLadekranRoute: ServicesLadekranRoute,
  ServicesShowroomRoute: ServicesShowroomRoute,
  DachIndexRoute: DachIndexRoute,
  FassadeIndexRoute: FassadeIndexRoute,
  HolzbauIndexRoute: HolzbauIndexRoute,
  KarriereIndexRoute: KarriereIndexRoute,
  KontaktIndexRoute: KontaktIndexRoute,
  RatgeberIndexRoute: RatgeberIndexRoute,
  ReferenzenIndexRoute: ReferenzenIndexRoute,
  RestaurierungIndexRoute: RestaurierungIndexRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
